config/routes.rb
Rails.application.routes.draw do
  resources :departamentos
  get "produtos/busca", to: "produtos#busca", as: :busca_produto
  resources :produtos
  root to: "produtos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/departamento.rb
class Departamento < ApplicationRecord
    has_many :produtos

    validates :nome, presence: true
end

app/models/produto.rb
class Produto < ApplicationRecord
    belongs_to :departamento, optional: true


    validates :nome, presence: true
    validates :descricao, presence: true
    validates :preco, presence: true
    validates :quantidade, presence: true
    validates :descricao, length: { minimum: 15 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: [:show, :edit, :update, :destroy]

  # GET /departamentos
  # GET /departamentos.json
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1
  # GET /departamentos/1.json
  def show
    @produtos_por_departamento = Produto.where("departamento_id = ?", params[:id])
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos
  # POST /departamentos.json
  def create
    @departamento = Departamento.new(departamento_params)

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to @departamento, notice: 'Departamento criado com sucesso!' }
        format.json { render :show, status: :created, location: @departamento }
      else
        format.html { render :new }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departamentos/1
  # PATCH/PUT /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to @departamento, notice: 'Departamento atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1
  # DELETE /departamentos/1.json
  def destroy
    @departamento.destroy
    respond_to do |format|
      format.html { redirect_to departamentos_url, notice: 'Departamento removido com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def departamento_params
      params.require(:departamento).permit(:nome)
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

    before_action :set_produto, only: [:edit, :update, :destroy]

    def index
        @produtos = Produto.order(name: :desc).limit 6
        @produto_com_desconto = Produto.order(:preco).limit 1
    end

    def create
        @produto = Produto.new produto_params
        set_departamentos
        if @produto.save
            flash[:notice] = "Produto salvo com sucesso!"
            redirect_to root_path
        else
            set_departamentos
            render :new
        end
    end

    def new
        @produto = Produto.new
        set_departamentos
    end

    def destroy
        @produto.destroy
        if @produto.destroy
            flash[:notice] = "Produto deletado com sucesso!"
            redirect_to root_path
        else
            render :index
        end
    end

    def edit
        set_departamentos   
        render :edit     
    end

    def update
        if @produto.update produto_params
            redirect_to root_path
            flash[:notice] = "Editado com sucesso!"
        else
            set_departamentos 
            render :edit
        end
    end

    def busca
        @nome = params[:nome]
        @produtos = Produto.where "nome like ?", "%#{@nome}%"
    end

    private

    def produto_params
        params.require(:produto).permit(:nome, :descricao, :preco, :quantidade, :departamento_id)
    end

    def set_produto
        @produto = Produto.find(params[:id])
    end

    def set_departamentos
        @departamentos = Departamento.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/departamentos/_form.html.erb
<%= form_with(model: departamento, local: true) do |form| %>
  <% if departamento.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% departamento.errors.full_messages.each do |message| %>
          <div class="alert alert-danger" role="alert"><%= message %></div>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="col-sm-8">
      <div class="form-group">
        <%= form.label :nome %>
        <%= form.text_field :nome %>
      </div>
    </div>  
  </div>  

  <div class="field">
    <div class="col-sm-8">
      <div class="form-group">
          <%= form.submit class:"btn btn-success" %>
      </div>
    </div>
  </div>         
<% end %>

app/views/departamentos/edit.html.erb
<h1>Editing Departamento</h1>

<%= render 'form', departamento: @departamento %>

<%= link_to 'Show', @departamento %> |
<%= link_to 'Back', departamentos_path %>

app/views/departamentos/index.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
    </div>    
<% end %> 

<h1>Departamentos</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departamentos.each do |departamento| %>
      <tr>
        <td><%= departamento.nome %></td>
        <td><%= link_to 'Ver', departamento, class:"btn btn-success" %></td>
        <td><%= link_to 'Editar', edit_departamento_path(departamento), class:"btn btn-info" %></td>
        <td><%= link_to 'Remover', departamento, method: :delete, class:"btn btn-danger", data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Departamento', new_departamento_path, class:"btn btn-primary" %>

app/views/departamentos/new.html.erb
<h1>Novo Departamento</h1>

<%= render 'form', departamento: @departamento %>


<div class="field">
    <div class="col-sm-8">
        <div class="form-group">
            <%= link_to 'Back', departamentos_path, class:"btn btn-primary" %>
        </div>
    </div>  
</div>  

app/views/departamentos/show.html.erb
<div class="alert alert-success" role="alert">
    <p id="notice"><%= notice %></p>
</div>    

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>Nome</td>
            <td>Descrição</td>
            <td>Departamento</td>
            <td>Preço</td>
            <td>Quantidade</td>
        </tr>
    </thead>
    <tbody>
    <% @produtos_por_departamento.each do |produto| %>    
        <tr>
            <td><%= produto.nome %></td>
            <td><%= produto.descricao %></td>
            <td><%= produto.departamento.nome %></td>
            <td><%= produto.preco %></td>
            <td><%= produto.quantidade %></td>
        </tr>
    <% end %>    
    </tbody>
</table>


<div class="field">
    <div class="col-sm-8">
        <div class="form-group">
          <%= link_to 'Editar', edit_departamento_path(@departamento), class:"btn btn-primary" %>
        </div>
    </div>
</div>

<div class="field">
    <div class="col-sm-8">
        <div class="form-group">
            <%= link_to 'Voltar', departamentos_path, class:"btn btn-secondary" %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Devmarket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= nav_bar brand: "Dev_Market", brand_link: root_url do %>
      <%= menu_group do %>
        <%= menu_item "Novo Produto", new_produto_path %>
        <%= menu_item "Departamentos", departamentos_path %>
      <% end %>
      <%= form_tag busca_produto_path, method: :get, class:"navbar-form navbar-right"  do %>
        <div class="form-group">
          <%= text_field_tag :nome, @nome, class:"form-control"%>
          <%= button_to "Buscar", nil, class:"btn btn-default"%>
        </div>  
      <% end %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/produtos/busca.html.erb
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>Nome</td>
            <td>Descrição</td>
            <td>Departamento</td>
            <td>Preço</td>
            <td>Quantidade</td>
            <td colspan='1'>
        </tr>
    </thead>
    <tbody>
    <% @produtos.each do |produto| %>    
        <tr>
            <td><%= produto.nome %></td>
            <td><%= produto.descricao %></td>
            <td><%= produto.departamento.nome %></td>
            <td><%= produto.preco %></td>
            <td><%= produto.quantidade %></td>
            <td><%= button_to "Remover", produto, method: :delete, class:"btn btn-danger",
            data: {confirm: "Deseja remover o produto #{produto.nome}?"} %></td>
        </tr>
    <% end %>    
    </tbody>
</table>

app/views/produtos/edit.html.erb
<%= form_for @produto do |form| %>

    <div class="row">
        <div class="col-sm-8">
            <div class="form-group">
                <%= form.label :nome %>
                <%= form.text_field :nome, class:"form-control" %>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-8">
            <div class="form-group">
                <%= form.label :descrição %>
                <%= form.text_area :descricao, class:"form-control", rows:4 %>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-2">
            <div class="form-group">
                <%= form.label :departamento %>
                <%= form.collection_select :departamento_id, @departamentos, :id, :nome, class:"form-control" %>
            </div>
        </div>    
    </div>

    <div class="row">
        <div class="col-sm-2">
            <div class="form-group">
                <%= form.label :preço %>
                <%= form.number_field :preco, step:0.01, class:"form-control" %>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-2">
            <div class="form-group">
                <%= form.label :quantidade %>
                <%= form.number_field :quantidade, class:"form-control" %>
            </div>
        </div>
    </div>

<%= form.submit "Editar", class:"btn btn-primary" %>            
<% end %>

app/views/produtos/index.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
    </div>    
<% end %>    


<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>Nome</td>
            <td>Descrição</td>
            <td>Departamento</div>
            <td>Preço</td>
            <td>Quantidade</td>
            <td colspan='1'>
        </tr>
    </thead>
    <tbody>
    <% @produtos.each do |produto| %>    
        <tr>
            <td><%= produto.nome %></td>
            <td><%= produto.descricao %></td>
            <td><%= produto.departamento.nome %></td>
            <td><%= produto.preco %></td>
            <td><%= produto.quantidade %></td>
            <td><%= link_to 'Editar', edit_produto_path(produto), class:"btn btn-info" %></td>
            <td><%= button_to "Remover", produto, method: :delete, class:"btn btn-danger",
            data: {confirm: "Deseja remover o produto #{produto.nome}?"} %></td>
        </tr>
    <% end %>    
    </tbody>
</table>
<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Produto com desconto</h4>
</div>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>Nome</td>
            <td>Descrição</td>
            <td>Departamento</td>
            <td>Preço</td>
            <td>Quantidade</td>
        </tr>
    </thead>
    <tbody>
    <% @produto_com_desconto.each do |produto| %>    
        <tr>
            <td><%= produto.nome %></td>
            <td><%= produto.descricao %></td>
            <td><%= produto.departamento.nome %></td>
            <td><%= produto.preco %></td>
            <td><%= produto.quantidade %></td>
        </tr>
    <% end %>    
    </tbody>
</table>

app/views/produtos/new.html.erb
<% @produto.errors.full_messages.each do |mensagem| %>
    <div class="alert alert-danger" role="alert"><%= mensagem %></div>
<% end %>


<%= form_for @produto do |form| %>

    <div class="row">
        <div class="col-sm-8">
            <div class="form-group">
                <%= form.label :nome %>
                <%= form.text_field :nome, class:"form-control" %>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-8">
            <div class="form-group">
                <%= form.label :descrição %>
                <%= form.text_area :descricao, class:"form-control", rows:4 %>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-2">
            <div class="form-group">
                <%= form.label :departamento %>
                <%= form.collection_select :departamento, @departamentos, :id, :nome,
                {}, class:"form-control" %>
            </div>
        </div>    
    </div>

    <div class="row">
        <div class="col-sm-2">
            <div class="form-group">
                <%= form.label :preço %>
                <%= form.number_field :preco, step:0.01, class:"form-control" %>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-2">
            <div class="form-group">
                <%= form.label :quantidade %>
                <%= form.number_field :quantidade, class:"form-control" %>
            </div>
        </div>
    </div>

<%= form.submit "Criar", class:"btn btn-primary" %>            
<% end %>